# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'picmi'
copyright = '2018, PICMI contributors'
author = 'PICMI contributors'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinxcontrib.autodoc_pydantic',
]
autodoc_member_order = 'bysource'
# Document members (incl. pydantic fields) so the auto-generated parameter list
# (from each Field(description=...)) is rendered for every documented class.
# ``undoc-members`` is required because pydantic fields carry no __doc__ (their text
# lives in Field(description=...)); without it autodoc skips them as "undocumented".
autodoc_default_options = {'members': True, 'undoc-members': True}

# -- autodoc-pydantic ---------------------------------------------------------
# Render the pydantic-based PICMI classes (and downstream extensions) as a clean
# list of documented fields, taken from each Field(description=...).  The noisy
# pydantic internals (JSON schema, config/validator summaries) are hidden.
# Hide the (very long) full field list from the class signature; the parameters are
# documented individually as the field list below instead.
autodoc_pydantic_model_hide_paramlist = True
autodoc_pydantic_model_show_json = False
autodoc_pydantic_model_show_config_summary = False
autodoc_pydantic_model_show_validator_summary = False
autodoc_pydantic_model_show_validator_members = False
autodoc_pydantic_model_show_field_summary = False
# Group members by type so all parameters (pydantic fields) are listed first as one
# block, followed by methods and properties (mirrors the old "Parameters first" layout).
autodoc_pydantic_model_member_order = 'groupwise'
autodoc_pydantic_field_list_validators = False
autodoc_pydantic_field_show_constraints = False
autodoc_pydantic_field_show_default = True
# Render each field as "parameter <name>" instead of the default "field <name>".
autodoc_pydantic_field_signature_prefix = 'parameter'
# Show downstream extension inputs under their user-facing ``<code>_`` alias.
autodoc_pydantic_field_show_alias = True
autodoc_pydantic_field_swap_name_and_alias = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
#html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'picmidoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'picmi.tex', 'picmi Documentation',
     'J.L. Vay et al.', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'picmi', 'picmi Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'picmi', 'picmi Documentation',
     author, 'picmi', 'One line description of project.',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/': None}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


def setup(app):
    """Post-process the reST that autodoc-pydantic generates for pydantic PICMI models
    (we do not reimplement any autodoc internals). Two passes:

    1. Insert ``Parameters`` / ``Methods`` / ``Attributes`` / ``Properties`` rubric
       headers between the groupwise member groups, so the long field list is visually
       separated from the methods and properties.
    2. Strip the ``:type:`` / ``:value:`` of class attributes whose value is just an
       object repr (e.g. the ``extension`` handle), so they render as a bare name instead
       of ``extension: ClassVar[Any] = <... object>``.
    """
    import re

    from sphinxcontrib.autodoc_pydantic.directives.autodocumenters import (
        PydanticModelDocumenter,
    )

    # Directive emitted for each member type -> rubric label (groupwise order).
    group_labels = [
        (".. py:pydantic_field::", "Parameters"),
        (".. py:method::", "Methods"),
        (".. py:attribute::", "Attributes"),
        (".. py:property::", "Properties"),
    ]
    object_repr = re.compile(r":value:\s*<.* object.*>")

    class GroupedPydanticModelDocumenter(PydanticModelDocumenter):
        def document_members(self, all_members: bool = False) -> None:
            result = self.directive.result
            start = len(result.data)
            super().document_members(all_members)

            # Pass 2: drop ``:type:``/``:value:`` for object-repr attributes.
            to_delete = []
            i = start
            while i < len(result.data):
                if result.data[i].lstrip().startswith(".. py:attribute::"):
                    opts, j = {}, i + 1
                    while j < len(result.data):
                        m = re.match(r":(\w+):", result.data[j].strip())
                        if not m:
                            break
                        opts[m.group(1)] = j
                        j += 1
                    if "value" in opts and object_repr.search(result.data[opts["value"]].strip()):
                        to_delete += [opts[k] for k in ("type", "value") if k in opts]
                    i = j
                else:
                    i += 1
            for idx in sorted(to_delete, reverse=True):
                del result[idx]

            # Pass 1: insert group rubrics before the first member of each type.
            insertions = []
            seen = set()
            for i in range(start, len(result.data)):
                stripped = result.data[i].lstrip()
                for prefix, label in group_labels:
                    if stripped.startswith(prefix) and label not in seen:
                        seen.add(label)
                        line = result.data[i]
                        indent = line[: len(line) - len(stripped)]
                        insertions.append((i, indent, label))
            for i, indent, label in reversed(insertions):
                src, offset = result.info(i)
                result.insert(i, "", src, offset)
                result.insert(i, f"{indent}.. rubric:: {label}", src, offset)
                result.insert(i, "", src, offset)

    app.setup_extension("sphinxcontrib.autodoc_pydantic")
    app.add_autodocumenter(GroupedPydanticModelDocumenter, override=True)
